"""Self-building skill system.

The agent can detect capability gaps and generate new skills on the fly:
generate SKILL.md + main.py, validate via AST, test in sandbox,
stage for user approval, then hot-reload.
"""

from __future__ import annotations

import ast
import asyncio
import json
import shutil
import sys
import textwrap
from dataclasses import dataclass, field
from datetime import datetime
from pathlib import Path
from typing import TYPE_CHECKING, Any

import structlog

if TYPE_CHECKING:
    from agent.config import SkillBuilderConfig
    from agent.core.events import EventBus
    from agent.llm.provider import LLMProvider
    from agent.skills.manager import SkillManager

logger = structlog.get_logger(__name__)

# Patterns blocked in generated code for safety
BLOCKED_PATTERNS = {
    "eval(",
    "exec(",
    "os.system(",
    "subprocess.Popen(",
    "subprocess.call(",
    "subprocess.run(",
    "__import__(",
    "importlib.import_module(",
    "compile(",
    "globals(",
    "locals(",
    "open(",  # file I/O should go through agent tools
}


@dataclass
class GeneratedSkill:
    """A skill generated by the builder."""

    name: str
    display_name: str
    description: str
    skill_md: str
    main_py: str
    permissions: list[str] = field(default_factory=lambda: ["safe"])


@dataclass
class ValidationResult:
    """Result of AST validation on generated code."""

    valid: bool
    errors: list[str] = field(default_factory=list)
    warnings: list[str] = field(default_factory=list)


@dataclass
class TestResult:
    """Result of sandbox testing a generated skill."""

    passed: bool
    output: str = ""
    error: str = ""
    duration_ms: int = 0


@dataclass
class SkillBuildResult:
    """Final result of the skill building pipeline."""

    success: bool
    skill_name: str
    staging_path: str | None = None
    error: str | None = None
    validation: ValidationResult | None = None
    test: TestResult | None = None
    retries: int = 0


# Few-shot exemplar for the LLM
_SKILL_EXEMPLAR = textwrap.dedent("""\
    # Example: A skill that provides a "greet" tool

    ## SKILL.md
    ```
    ---
    name: greeter
    display_name: Greeter
    description: A simple greeting skill
    version: "0.1.0"
    permissions:
      - safe
    triggers:
      - greet
      - hello
    ---

    # Greeter Skill

    Provides a greeting tool.
    ```

    ## main.py
    ```python
    from agent.skills.base import Skill


    class GreeterSkill(Skill):
        async def setup(self) -> None:
            self.register_tool(
                name="greet",
                description="Greet someone by name",
                function=self._greet,
                tier="safe",
            )

        async def _greet(self, name: str = "World") -> str:
            return f"Hello, {name}!"

        def get_system_prompt_extension(self) -> str | None:
            return "You have a greeter skill. Use greeter.greet to greet people."
    ```
""")


class SkillBuilder:
    """Builds new skills from natural language descriptions.

    Pipeline:
    1. Generate name (LLM call if not provided)
    2. Generate code (LLM call with few-shot exemplars)
    3. Validate via AST (syntax, Skill subclass, blocked patterns)
    4. Sandbox test (subprocess, 15s timeout)
    5. Stage to skills/_staging/<name>/
    6. Return result for user approval
    """

    def __init__(
        self,
        llm: LLMProvider | None,
        config: SkillBuilderConfig,
        event_bus: EventBus,
        skill_manager: SkillManager | None = None,
    ) -> None:
        self.llm = llm
        self.config = config
        self.event_bus = event_bus
        self.skill_manager = skill_manager
        self._staging_dir = Path(config.staging_dir)

    @property
    def staging_dir(self) -> Path:
        """Resolved staging directory."""
        return self._staging_dir.resolve()

    async def build_skill(
        self,
        description: str,
        name: str | None = None,
        permissions: list[str] | None = None,
    ) -> SkillBuildResult:
        """Orchestrate the full skill building pipeline.

        Args:
            description: Natural language description of the desired skill.
            name: Optional skill name. Generated by LLM if not provided.
            permissions: Optional permission tiers. Defaults to config max.

        Returns:
            SkillBuildResult with success status and staging path.
        """
        from agent.core.events import Events

        await self.event_bus.emit(
            Events.SKILL_BUILD_REQUESTED,
            {
                "description": description,
                "name": name,
            },
        )

        # Cap permissions
        if permissions is None:
            permissions = list(self.config.max_permissions)
        else:
            allowed = set(self.config.max_permissions)
            permissions = [p for p in permissions if p in allowed]
            if not permissions:
                permissions = ["safe"]

        # Step 1: Generate name
        if not name:
            name = await self._generate_name(description)

        # Sanitize name
        name = name.lower().replace(" ", "-").replace("_", "-")
        name = "".join(c for c in name if c.isalnum() or c == "-")

        logger.info("skill_build_started", name=name, description=description[:100])

        # Retry loop
        last_error = ""
        for attempt in range(self.config.max_retries):
            # Step 2: Generate code
            generated = await self._generate_code(name, description, permissions, last_error)

            # Step 3: Validate
            validation = self._validate_code(generated)
            if not validation.valid:
                last_error = "; ".join(validation.errors)
                logger.warning(
                    "skill_validation_failed",
                    name=name,
                    attempt=attempt + 1,
                    errors=validation.errors,
                )
                continue

            # Step 4: Stage files
            staging_path = self._stage_skill(generated)

            # Step 5: Sandbox test
            test_result = await self._sandbox_test(staging_path)
            if not test_result.passed:
                last_error = test_result.error
                logger.warning(
                    "skill_test_failed",
                    name=name,
                    attempt=attempt + 1,
                    error=test_result.error[:200],
                )
                # Clean up failed staging
                shutil.rmtree(staging_path, ignore_errors=True)
                continue

            # Step 6: Write auto-generated marker
            self._write_marker(staging_path, description)

            result = SkillBuildResult(
                success=True,
                skill_name=name,
                staging_path=str(staging_path),
                validation=validation,
                test=test_result,
                retries=attempt,
            )

            await self.event_bus.emit(
                Events.SKILL_BUILD_COMPLETED,
                {
                    "name": name,
                    "success": True,
                    "retries": attempt,
                },
            )

            logger.info("skill_build_succeeded", name=name, retries=attempt)
            return result

        # All retries exhausted
        result = SkillBuildResult(
            success=False,
            skill_name=name,
            error=f"Failed after {self.config.max_retries} attempts. Last error: {last_error}",
            retries=self.config.max_retries,
        )

        await self.event_bus.emit(
            Events.SKILL_BUILD_COMPLETED,
            {
                "name": name,
                "success": False,
                "error": result.error,
            },
        )

        return result

    async def approve_skill(self, name: str) -> str:
        """Move a staged skill to the active skills directory.

        Args:
            name: Skill name in staging.

        Returns:
            Status message.
        """
        staging_path = self.staging_dir / name
        if not staging_path.is_dir():
            return f"No staged skill found: {name}"

        # Determine target directory
        if self.skill_manager:
            target = self.skill_manager.skills_dir / name
        else:
            target = Path("skills") / name

        if target.exists():
            return f"Skill '{name}' already exists at {target}. Remove it first."

        target.parent.mkdir(parents=True, exist_ok=True)
        shutil.move(str(staging_path), str(target))

        logger.info("skill_approved", name=name, path=str(target))
        return (
            f"Skill '{name}' approved and moved to {target}. "
            "It will be loaded within ~5 seconds."
        )

    async def reject_skill(self, name: str) -> str:
        """Delete a staged skill.

        Args:
            name: Skill name in staging.

        Returns:
            Status message.
        """
        staging_path = self.staging_dir / name
        if not staging_path.is_dir():
            return f"No staged skill found: {name}"

        shutil.rmtree(staging_path)
        logger.info("skill_rejected", name=name)
        return f"Staged skill '{name}' deleted."

    def list_staged(self) -> list[dict[str, Any]]:
        """List all staged skills.

        Returns:
            List of dicts with skill name and metadata.
        """
        if not self.staging_dir.is_dir():
            return []

        staged: list[dict[str, Any]] = []
        for entry in sorted(self.staging_dir.iterdir()):
            if not entry.is_dir() or entry.name.startswith("."):
                continue
            skill_md = entry / "SKILL.md"
            main_py = entry / "main.py"
            marker = entry / ".auto_generated"

            info: dict[str, Any] = {
                "name": entry.name,
                "has_skill_md": skill_md.is_file(),
                "has_main_py": main_py.is_file(),
            }

            if marker.is_file():
                try:
                    marker_data = json.loads(marker.read_text(encoding="utf-8"))
                    info["description"] = marker_data.get("description", "")
                    info["created_at"] = marker_data.get("created_at", "")
                except (json.JSONDecodeError, OSError):
                    pass

            staged.append(info)

        return staged

    # --- Internal pipeline steps ---

    async def _generate_name(self, description: str) -> str:
        """Generate a skill name from description via LLM."""
        messages = [
            {
                "role": "system",
                "content": (
                    "Generate a short kebab-case skill name (e.g. 'weather-fetch', "
                    "'code-review') for the described capability. "
                    "Reply with ONLY the name, nothing else."
                ),
            },
            {"role": "user", "content": description},
        ]
        system_msg = (
            "Generate a short kebab-case skill name (e.g. 'weather-fetch', "
            "'code-review') for the described capability. "
            "Reply with ONLY the name, nothing else."
        )
        if self.llm is not None:
            response = await self.llm.completion(messages=messages)
            content = response.content
        else:
            from agent.llm.fallback import llm_complete

            content = await llm_complete(prompt=description, system=system_msg)
        name = content.strip().strip("'\"` \n")
        return name or "custom-skill"

    async def _generate_code(
        self,
        name: str,
        description: str,
        permissions: list[str],
        previous_error: str = "",
    ) -> GeneratedSkill:
        """Generate SKILL.md and main.py via LLM."""
        error_context = ""
        if previous_error:
            error_context = (
                f"\n\nPrevious attempt failed with error:\n{previous_error}\n"
                "Fix these issues in your new attempt."
            )

        messages = [
            {
                "role": "system",
                "content": (
                    "You are a skill code generator for an AI agent framework. "
                    "Generate a SKILL.md file and a main.py file for the described skill.\n\n"
                    "Rules:\n"
                    "- main.py MUST have a class inheriting "
                    "`agent.skills.base.Skill`\n"
                    "- MUST implement `async def setup(self)` "
                    "calling `self.register_tool()`\n"
                    "- Tool functions must be `async def` methods\n"
                    "- Do NOT use eval(), exec(), os.system(), "
                    "subprocess, open(), __import__(), compile()\n"
                    "- Use only stdlib and common packages\n"
                    f"- Allowed permission tiers: {permissions}\n"
                    "- Include `get_system_prompt_extension()`\n\n"
                    "Respond in this exact JSON format:\n"
                    '{"skill_md": "...", "main_py": "..."}\n\n'
                    f"Example:\n{_SKILL_EXEMPLAR}"
                    f"{error_context}"
                ),
            },
            {
                "role": "user",
                "content": f"Create a skill named '{name}' that: {description}",
            },
        ]

        if self.llm is not None:
            response = await self.llm.completion(messages=messages)
            content = response.content.strip()
        else:
            from agent.llm.fallback import llm_complete

            content = (
                await llm_complete(
                    prompt=f"Create a skill named '{name}' that: {description}",
                    system=messages[0]["content"],
                )
            ).strip()

        # Parse JSON response
        try:
            # Try to extract JSON from the response
            start = content.find("{")
            end = content.rfind("}") + 1
            if start >= 0 and end > start:
                data = json.loads(content[start:end])
            else:
                raise ValueError("No JSON object found in response")
        except (json.JSONDecodeError, ValueError):
            # Fallback: try to extract code blocks
            data = self._extract_from_markdown(content, name)

        skill_md = data.get("skill_md", "")
        main_py = data.get("main_py", "")

        # Build display name from name
        display_name = name.replace("-", " ").replace("_", " ").title()

        return GeneratedSkill(
            name=name,
            display_name=display_name,
            description=description,
            skill_md=skill_md,
            main_py=main_py,
            permissions=permissions,
        )

    def _extract_from_markdown(self, content: str, name: str) -> dict[str, str]:
        """Fallback: extract SKILL.md and main.py from markdown code blocks."""
        blocks: list[str] = []
        in_block = False
        current: list[str] = []

        for line in content.split("\n"):
            if line.strip().startswith("```"):
                if in_block:
                    blocks.append("\n".join(current))
                    current = []
                    in_block = False
                else:
                    in_block = True
            elif in_block:
                current.append(line)

        result: dict[str, str] = {"skill_md": "", "main_py": ""}
        for block in blocks:
            if "---" in block and "name:" in block:
                result["skill_md"] = block
            elif "class " in block and "Skill" in block:
                result["main_py"] = block

        return result

    def _validate_code(self, skill: GeneratedSkill) -> ValidationResult:
        """Validate generated code via AST analysis."""
        errors: list[str] = []
        warnings: list[str] = []

        if not skill.skill_md.strip():
            errors.append("SKILL.md is empty")

        if not skill.main_py.strip():
            errors.append("main.py is empty")
            return ValidationResult(valid=False, errors=errors)

        # Check for YAML frontmatter in SKILL.md
        if "---" not in skill.skill_md:
            errors.append("SKILL.md missing YAML frontmatter (--- delimiters)")

        # AST parse check
        try:
            tree = ast.parse(skill.main_py)
        except SyntaxError as e:
            errors.append(f"Syntax error in main.py: {e}")
            return ValidationResult(valid=False, errors=errors)

        # Check for Skill subclass
        has_skill_subclass = False
        for node in ast.walk(tree):
            if isinstance(node, ast.ClassDef):
                for base in node.bases:
                    base_name = ""
                    if isinstance(base, ast.Name):
                        base_name = base.id
                    elif isinstance(base, ast.Attribute):
                        base_name = base.attr
                    if base_name == "Skill":
                        has_skill_subclass = True

        if not has_skill_subclass:
            errors.append("No class inheriting from Skill found in main.py")

        # Check for blocked patterns
        code_str = skill.main_py
        for pattern in BLOCKED_PATTERNS:
            if pattern in code_str:
                errors.append(f"Blocked pattern found: {pattern}")

        # Check for setup method
        if "async def setup" not in code_str:
            errors.append("Missing 'async def setup' method")

        if not errors and "register_tool" not in code_str:
            warnings.append("No register_tool() call found - skill may not provide tools")

        return ValidationResult(
            valid=len(errors) == 0,
            errors=errors,
            warnings=warnings,
        )

    def _stage_skill(self, skill: GeneratedSkill) -> Path:
        """Write generated skill files to staging directory."""
        staging_path = self.staging_dir / skill.name
        staging_path.mkdir(parents=True, exist_ok=True)

        (staging_path / "SKILL.md").write_text(skill.skill_md, encoding="utf-8")
        (staging_path / "main.py").write_text(skill.main_py, encoding="utf-8")

        logger.debug("skill_staged", name=skill.name, path=str(staging_path))
        return staging_path

    async def _sandbox_test(self, skill_path: Path) -> TestResult:
        """Test a skill in a subprocess sandbox.

        Imports the skill's main.py, instantiates the Skill subclass,
        calls setup(), and verifies tools were registered.
        """
        test_script = textwrap.dedent(f"""\
            import sys
            import json
            sys.path.insert(0, {str(skill_path.parent.parent)!r})
            sys.path.insert(0, {str(skill_path)!r})

            # Minimal stubs for testing
            class FakeEventBus:
                def on(self, *a, **kw): pass
                def off(self, *a, **kw): pass

            class FakeScheduler:
                pass

            class FakeRegistry:
                def __init__(self):
                    self._tools = {{}}
                def tool(self, name, description, tier="safe", category="skill"):
                    def dec(fn):
                        self._tools[name] = fn
                        return fn
                    return dec
                def unregister_tool(self, name): pass

            import importlib.util
            main = r"{skill_path / 'main.py'}"
            spec = importlib.util.spec_from_file_location("skill_module", main)
            mod = importlib.util.module_from_spec(spec)
            spec.loader.exec_module(mod)

            import inspect
            from agent.skills.base import Skill
            skill_cls = None
            for name, obj in inspect.getmembers(mod, inspect.isclass):
                if issubclass(obj, Skill) and obj is not Skill:
                    skill_cls = obj
                    break

            if skill_cls is None:
                print(json.dumps({{"error": "No Skill subclass found"}}))
                sys.exit(1)

            import asyncio

            async def run_test():
                reg = FakeRegistry()
                bus = FakeEventBus()
                sched = FakeScheduler()
                from agent.skills.base import SkillMetadata
                meta = SkillMetadata(name="test")
                instance = skill_cls(
                    metadata=meta,
                    tool_registry=reg,
                    event_bus=bus,
                    scheduler=sched,
                )
                await instance.setup()
                return len(reg._tools)

            tool_count = asyncio.run(run_test())
            print(json.dumps({{"success": True, "tools": tool_count}}))
        """)

        start = asyncio.get_event_loop().time()
        try:
            proc = await asyncio.create_subprocess_exec(
                sys.executable,
                "-c",
                test_script,
                stdout=asyncio.subprocess.PIPE,
                stderr=asyncio.subprocess.PIPE,
                cwd=str(skill_path.parent),
            )
            stdout, stderr = await asyncio.wait_for(proc.communicate(), timeout=15.0)
            duration_ms = int((asyncio.get_event_loop().time() - start) * 1000)

            output = stdout.decode(errors="ignore").strip()
            error_output = stderr.decode(errors="ignore").strip()

            if proc.returncode != 0:
                return TestResult(
                    passed=False,
                    output=output,
                    error=error_output or output or f"Exit code: {proc.returncode}",
                    duration_ms=duration_ms,
                )

            # Parse output
            try:
                result_data = json.loads(output)
                if result_data.get("error"):
                    return TestResult(
                        passed=False,
                        output=output,
                        error=result_data["error"],
                        duration_ms=duration_ms,
                    )
                return TestResult(
                    passed=True,
                    output=f"Registered {result_data.get('tools', 0)} tool(s)",
                    duration_ms=duration_ms,
                )
            except json.JSONDecodeError:
                return TestResult(
                    passed=False,
                    output=output,
                    error="Could not parse test output",
                    duration_ms=duration_ms,
                )

        except TimeoutError:
            duration_ms = int((asyncio.get_event_loop().time() - start) * 1000)
            return TestResult(
                passed=False,
                error="Sandbox test timed out (15s limit)",
                duration_ms=duration_ms,
            )
        except Exception as e:
            return TestResult(
                passed=False,
                error=f"Sandbox error: {e}",
            )

    def _write_marker(self, skill_path: Path, description: str) -> None:
        """Write .auto_generated marker with metadata."""
        marker_data = {
            "auto_generated": True,
            "description": description,
            "created_at": datetime.now().isoformat(),
            "builder_version": "1.0",
        }
        (skill_path / ".auto_generated").write_text(
            json.dumps(marker_data, indent=2), encoding="utf-8"
        )
